apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seq-input-gelf.fullname" . }}
  labels:
    {{- include "seq-input-gelf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "seq-input-gelf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "seq-input-gelf.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "seq-input-gelf.serviceAccountName" . }}
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gelf
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          readinessProbe:
            tcpSocket:
              port: gelf
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: gelf
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SEQ_ADDRESS
              value: {{ .Values.seq.url }}
            - name: SEQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.seq.apiKey.secretName }}
                  key: {{ .Values.seq.apiKey.secretKey }}
            - name: GELF_ADDRESS
              value: {{ printf "%s://0.0.0.0:%d" ( lower .Values.service.protocol ) ( .Values.service.port | int ) }}
            - name: GELF_ENABLE_DIAGNOSTICS
              value: {{ .Values.seq.diagnosticLogging | quote }}
            {{- if (and (eq (lower .Values.service.protocol) "tcp" ) .Values.seq.tls.enabled ) }}
            - name: GELF_CERTIFICATE_PATH
              value: {{ printf "/certs/%s" .Values.seq.tls.certificateSecretKey }}
            - name: GELF_CERTIFICATE_PRIVATE_KEY_PATH
              value: {{ printf "/certs/%s" .Values.seq.tls.privateKeySecretKey }}
            {{- end }}
            - name: RUST_BACKTRACE
              value: {{ .Values.seq.rustBackTrace | quote }}
          volumeMounts:
            # mount an empty dir to /tmp to prevent errors as readOnlyRootFilesystem is true
            - mountPath: /tmp
              name: tmp
            {{- if (and (eq (lower .Values.service.protocol) "tcp" ) .Values.seq.tls.enabled ) }}
            - mountPath: /certs
              name: certs
              readOnly: true
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if (and (eq (lower .Values.service.protocol) "tcp" ) .Values.seq.tls.enabled ) }}
        - name: certs
          secret:
            secretName: {{ .Values.seq.tls.secretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
