{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seq-input-gelf.serviceAccountName" . }}
  labels:
    {{- include "seq-input-gelf.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ .Values.seq.apiKey.secretName }}
{{- end }}
