repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-yaml
        exclude: 'deploy/helm'
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'deploy/helm/README.md'

  - repo: https://github.com/syntaqx/git-hooks
    rev: 'v0.0.17'
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/Jarmos-san/shellcheck-precommit
    rev: 'v0.2.0'
    hooks:
      - id: shellcheck-system

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts

ci:
  autoupdate_schedule: weekly
